article:
  auto_cover: false
  license: '本文採用 [姓名標示-非商業性-相同方式分享 4.0 國際](https://creativecommons.org/licenses/by-nc-sa/4.0/) 授權條款。轉載請標示來源。'
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    title: 推薦文章
    max_count: 5
comments:
  service: utterances # utterances
  utterances:
    repo: pan93412/pan.blog-comments
sidebar:
  logo:
    avatar: '[config.avatar](/)'
plugins:
  # heti:
  #   enable: true
  mathjax:
    enable: true
footer:
  content: |
    本站由 [@pan93412](https://pan93.com) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主題建立。
    本 blog 所有文章除特別聲明外，均採用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 授權條款，轉載請標明出處。
style:
  font-family:
    body: '"HarmonyOS Sans TC", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"JetBrains Mono", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
