article:
  auto_cover: false
  license: '本文採用 [姓名標示-非商業性-相同方式分享 4.0 國際](https://creativecommons.org/licenses/by-nc-sa/4.0/) 授權條款。轉載請標示來源。'
  # npm i hexo-related-popular-posts
  related_posts:
    enable: false
    title: 推薦文章
    max_count: 5
comments:
  service: utterances # utterances
  utterances:
    repo: pan93412/pan.blog-comments
sidebar:
  logo:
    avatar: '[config.avatar](/)'
heti: true
