name: 建置 pan.blog

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: 簽出版本庫
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 使用 Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2.0.1
        name: 安裝 PNPM

      - name: 取得 PNPM 儲存區的位置
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: 設定 PNPM 快取
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安裝相依關係
        run: npm install

      - name: 建置
        run: npm run build

      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
  