name: 建置 pan.blog

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: 簽出版本庫
        uses: actions/checkout@v2
      - name: 簽出子模組 (submodule)
        uses: textbook/git-checkout-submodule-action@master
      - name: 使用 Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: 快取 NPM 的相依關係
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: 安裝相依關係
        run: npm install
      - name: 建置
        run: npm run build
      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch